vim.keymap.set('n', '<space>wv', ':vsp<cr>', opts)
vim.keymap.set('n', '<space>ws', ':sp<cr>', opts)
vim.keymap.set('n', '<space>wc', ':close<cr>', opts)
vim.keymap.set('n', '<space>o-', ':edit %:p:h', opts)
vim.keymap.set('n', '<space><space>', ':Telescope find_files<cr>', opts)
vim.keymap.set('n', '<space>/', ':Telescope live_grep<cr>', opts)
vim.keymap.set('n', '<space>bb', ':Telescope buffers<cr>', opts)
vim.keymap.set('n', '<space>op', ':NvimTreeToggle<cr>', opts)
vim.keymap.set('n', '<space>gg', ':Neogit<cr>', opts)
